import string
from math import sqrt
from math import ceil

# Convert string from plain text into normalized form:
# 1) All non-alphanumerical characters removed
# 2) All whitespace removed
# 3) All alphabetical characters converted to lowercase
# (.lower() is better than .casefold() due to casing being for output)
def normalize(plain_text):
    
    tran_tab = {k: '' for k in string.punctuation}
    tran_tab = tran_tab | {k: '' for k in string.whitespace}
    tran_tab = str.maketrans(tran_tab)
    
    normalized_text = str.translate(plain_text, tran_tab).lower()
    
    return normalized_text

# Enciphers the normalized text
# 1) Calculates c, r. Since c * r >= len(normal_text), *ceiling* should be used
# (Credit to seggiepants for pointing this out in their solution)
# 2) the normalized text is padded with the necessary number of blank spaces
# 3) chunks are generated by a double iteration involving a c-sized step to
# get the correct characters from each row.
# (Again, credit to seggiepants for this)
def cipher(normal_text):
    
    c = ceil(sqrt(len(normal_text)))
    r = ceil(len(normal_text) / c)
        
    output = normal_text + ''.join([' '] * (c * r - len(normal_text)))
            
    output = ' '.join([output[i::c] for i in range(0, c)])
    
    return output

# Main function equivalent: doesn't do anything but call other functions
def cipher_text(plain_text):
    
    output = normalize(plain_text)
    
    # Only bother with enciphering if there is anything left after normalizing
    if output:
        output = cipher(output)
    
    return output